#!/usr/bin/env bash
set -e
set -x

cd "$(dirname "$0")/.."

# Fetch updates from iptv-org
git fetch iptv-org

# Sync ALL *.m3u files from iptv-org's streams/ folder
git checkout iptv-org/master -- streams/*.m3u

# Stage updated streams/ files
git add streams/

# Generate a combined index.m3u
SELECTED_FILES=("ca.m3u" "us.m3u" "uk.m3u" "au.m3u")

echo "#EXTM3U" > index.m3u
echo "# This is a combined playlist generated by GitHub Actions" >> index.m3u
echo "" >> index.m3u

for FILE in "${SELECTED_FILES[@]}"; do
  if [ -f "streams/$FILE" ]; then
    echo "# --- START $FILE ---" >> index.m3u
    cat "streams/$FILE" >> index.m3u
    echo "# --- END $FILE ---" >> index.m3u
    echo "" >> index.m3u
  else
    echo "Warning: streams/$FILE not found!" >&2
  fi
done

# Show diff for debugging
git diff index.m3u || true

# Stage index.m3u even if only it changed
git add index.m3u

# Commit if there are changes
git commit -m "Sync all streams/*.m3u and update index.m3u with combined playlist" || echo "No changes to commit"
