#!/usr/bin/env bash

# Move to the repo root (assuming this script lives in ./scripts/)
cd "$(dirname "$0")/.."

# Fetch updates from iptv-org
git fetch iptv-org

# Sync all *.m3u files from iptv-org to ./streams/, excluding streams/index.m3u if it exist
git checkout iptv-org/master -- streams/*.m3u
git rm --cached streams/index.m3u 2>/dev/null || true  # Ensure it's never tracked

# Add and commit any changes to streams/*.m3u
git add streams/*.m3u
git commit -m "Sync all streams/*.m3u from iptv-org" || echo "No changes in streams/"

# Generate a combined index.m3u
echo "#EXTM3U" > index.m3u
echo "# Combined playlist generated by GitHub Actions" >> index.m3u
echo "" >> index.m3u

# Use wildcard to automatically include all US-related .m3u files
SELECTED_FILES=(streams/us*.m3u streams/ca.m3u streams/uk.m3u streams/au.m3u)

for FILE in "${SELECTED_FILES[@]}"; do
  if [ -f "$FILE" ]; then
    # Remove redundant #EXTM3U lines when combining
    grep -v '^#EXTM3U' "$FILE" >> index.m3u
    echo "" >> index.m3u
  else
    echo "Warning: $FILE not found!" >&2
  fi
done

# Stage the updated index.m3u
git add index.m3u
git commit -m "Update index.m3u with combined playlist" || echo "No changes in index.m3u"
